/**
 * Stuff
 */
const obj = module.exports = {} ;

/**
 * parses the user-to-user information generated by avaya sbce
 * 
 * @param {*} data a string with the sip user-to-user information
 * @returns an object with the fields uuikey, ucid and encoding
 */
obj.parseSipUserToUser = (data) => {
    const regex = /([0-9A-F]{6})([0-9A-F]{16})\;(.*)/g;
  
    const result = regex.exec(data);
    return parseParams(data, {uuikey: result[1], ucid: result[2] || result[3] || ''});
}

function parseParams(data, params) {
    //let params = params || {};
  
    const regex = /\s*;\s*([\w\-.!%*_+`'~]+)(?:\s*=\s*([\w\-.!%*_+`'~]+|"[^"\\]*(\\.[^"\\]*)*"))?/g;
  
    for (let r = regex.exec(data); r; r = regex.exec(data)) {
      params[r[1].toLowerCase()] = r[2];
    }
  
    return params;
}
  