const config = require('config');
const assert = require('assert');
const Client = require('rtpengine-client').Client ;
const obj = module.exports = {} ;
//const debug = require('debug')('drachtio:siprec-recording-server');

obj.isFreeswitchSource = (req) => {
  console.log(`has token? ${req.has('X-Return-Token')}: ${req.get('X-Return-Token')}`);
  return req.has('X-Return-Token');
};

let idx = 0;
let servers;
obj.getAvailableFreeswitch = () => {
  servers = servers || config.get('freeswitch');
  if (idx == servers.length) idx = 0;
  return servers[idx++];
};


let idxRtpe = 0;
let rtpes;
obj.getAvailableRtpengine = () => {
  if (!rtpes) {
    let rtpEngines = config.get('rtpengine');
    rtpEngines = Array.isArray(rtpEngines) ? rtpEngines : [rtpEngines];
    rtpes = rtpEngines.map((r) => {
      const port = r.localPort || 0;
      const rtpe = new Client({port, timeout: 1500});
      rtpe.remote = r.remote;
      return rtpe;
    });
  }
  assert(rtpes.length > 0);
  if (idxRtpe == rtpes.length) idxRtpe = 0;
  return rtpes[idxRtpe++];
};

/**
 * parses the user-to-user information generated by avaya sbce
 * 
 * @param {*} data a string with the sip user-to-user information
 * @returns an object with the fields uuikey, ucid and encoding
 */
obj.parseSipUserToUser = (data) => {
  console.log("Moin")
  const regex = /([0-9A-F]{6})([0-9A-F]{16})\;(.*)/g;

  const result = regex.exec(data);
  console.log(`Moin : ${JSON.stringify(result)}` )
  return parseParams(data, {uuikey: result[1], ucid: result[2] || result[3] || ''});
}

function parseParams(data, params) {
  console.log("Moin Moin")
  //let params = params || {};

  const regex = /\s*;\s*([\w\-.!%*_+`'~]+)(?:\s*=\s*([\w\-.!%*_+`'~]+|"[^"\\]*(\\.[^"\\]*)*"))?/g;

  for (let r = regex.exec(data); r; r = regex.exec(data)) {
    params[r[1].toLowerCase()] = r[2];
  }

  console.log(`Moin Moin : ${JSON.stringify(params)}` )
  return params;
}